# Generated by Django 6.0.3 on 2026-03-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Claimed', 'Claimed'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20),
        ),
    ]
