# Generated by Django 6.0.3 on 2026-03-24 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequirementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=150)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_snapshots', to='core.application')),
            ],
        ),
    ]
